### ISSUE TITLE
Sur certain niveaux, j'ai pu voir que les objets de l'inventaire étaient affichés les uns sur les autres

### ISSUE THREAD

**Issue by Mokona** [Asso-MO5/room5#9]

**Comment by kazerlelutin** [comment]
traité ?

**Comment by Mokona** [comment]
Pas que je sache, je ne suis jamais arrivé à le reproduire.

Mais @aoineko-fr disait que ça se passait toujours.

**Comment by aoineko-fr** [comment]
Corrigé. En fait c'est juste que les objets utilisés ne disparaissaient plus
